### ISSUE TITLE
Create README.md for project overview

### ISSUE THREAD

**Issue by JavaHammes** [scherzma/Skunk#16]
A  `README.md` file is essential for providing newcomers with a clear and concise introduction to our project. We need to make the project more informative and facilitate contribution.

**Tasks:**

Outline basic README sections:
- [ ] Project title and short description
- [ ] Purpose and main features
- [ ] Technologies and frameworks used (not fully clear yet)
- [ ] Getting started instructions (not fully doable yet)
- [ ] How to contribute
- [ ] License information
